In [72]:
import pandas as pd
import os

In [73]:
BASEPATH = './raw_data/'
files = os.listdir(BASEPATH)

df_list = []
for file in files:
  if file == 'englandm.csv':
    df_list.append(pd.read_csv(BASEPATH + file, index_col=[0], low_memory=False))
    
    # Create standard: Home/Away team are referred to as Home and Away
    if 'HomeTeam' in df_list[-1].columns and 'AwayTeam' in df_list[-1].columns:
      df_list[-1]['Home'] = df_list[-1]['HomeTeam']
      df_list[-1]['Away'] = df_list[-1]['AwayTeam']
      df_list[-1].drop(['HomeTeam'], inplace=True, axis=1)
      df_list[-1].drop(['AwayTeam'], inplace=True, axis=1)

    # Create standard: Home/Away goals are referred to as FTHG and FTAG
    if 'HG' in df_list[-1].columns and 'AG' in df_list[-1].columns:
      df_list[-1]['FTHG'] = df_list[-1]['HG']
      df_list[-1]['FTAG'] = df_list[-1]['AG']
      df_list[-1].drop(['HG'], inplace=True, axis=1)
      df_list[-1].drop(['AG'], inplace=True, axis=1)

    # Create standard: Pinnacle odds are referred to as PH, PD and PA
    if 'PSH' in df_list[-1].columns and 'PSD' in df_list[-1].columns and 'PSA' in df_list[-1].columns:
      df_list[-1]['PH'] = df_list[-1]['PSH']
      df_list[-1]['PD'] = df_list[-1]['PSD']
      df_list[-1]['PA'] = df_list[-1]['PSA']
      df_list[-1].drop(['PSH'], inplace=True, axis=1)
      df_list[-1].drop(['PSD'], inplace=True, axis=1)
      df_list[-1].drop(['PSA'], inplace=True, axis=1)

    # Create standard: Home/Away goals are referred to as FTHG and FTAG
    if 'Div' in df_list[-1].columns:
      df_list[-1]['League'] = df_list[-1]['Div']
      df_list[-1].drop(['Div'], inplace=True, axis=1)

    # Create standard: Home/Away goals are referred to as FTHG and FTAG
    if 'Res' in df_list[-1].columns:
      df_list[-1]['FTR'] = df_list[-1]['Res']
      df_list[-1].drop(['Res'], inplace=True, axis=1)

df = pd.concat(df_list)
df

,Country,League,Season,Date,Time,Home,Away,PH,PD,PA,...,HBP,ABP,HT,AT,Unnamed: 28,Unnamed: 29,Unnamed: 51,Unnamed: 106,Unnamed: 52,Unnamed: 53
0,Argentina,Liga Profesional,2012/2013,03/08/2012,23:00,Arsenal Sarandi,Union de Santa Fe,1.90,3.39,5.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,Liga Profesional,2012/2013,04/08/2012,01:10,Velez Sarsfield,Argentinos Jrs,2.00,3.24,4.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Argentina,Liga Profesional,2012/2013,04/08/2012,18:10,Racing Club,Atl. Rafaela,1.91,3.34,5.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Argentina,Liga Profesional,2012/2013,04/08/2012,20:10,Colon Santa FE,Lanus,2.50,3.16,3.27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,Liga Profesional,2012/2013,04/08/2012,22:15,Quilmes,Boca Juniors,3.18,3.13,2.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8461,USA,MLS,2022,23/10/2022,18:00,CF Montreal,New York City,2.12,3.45,3.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8462,USA,MLS,2022,24/10/2022,01:00,Austin FC,FC Dallas,2.30,3.49,3.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8463,USA,MLS,2022,30/10/2022,19:00,Los Angeles FC,Austin FC,1.49,4.80,6.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8464,USA,MLS,2022,31/10/2022,00:00,Philadelphia Union,New York City,1.97,3.67,4.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8465,USA,MLS,2022,05/11/2022,20:00,Los Angeles FC,Philadelphia Union,1.71,4.13,4.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
for column in df:
  print(column, ':', df[column].isna().sum())
  if df[column].isna().sum() == 318728:
    df.drop([column], axis=1, inplace=True)

df

Country : 158501
League : 19018
Season : 158501
Date : 19018
Time : 141152
Home : 20064
Away : 20064
PH : 106093
PD : 106093
PA : 106093
MaxH : 141172
MaxD : 141172
MaxA : 141172
AvgH : 141172
AvgD : 141172
AvgA : 141172
FTHG : 19022
FTAG : 19022
FTR : 19022
HTHG : 124199
HTAG : 124199
HTR : 124199
HS : 198688
AS : 198688
HST : 199494
AST : 199494
HF : 200785
AF : 200785
HC : 199063
AC : 199063
HY : 198499
AY : 198498
HR : 198498
AR : 198499
B365H : 150542
B365D : 150542
B365A : 150542
BWH : 156422
BWD : 156422
BWA : 156422
IWH : 142710
IWD : 142710
IWA : 142714
WHH : 144966
WHD : 144966
WHA : 144966
VCH : 160894
VCD : 160895
VCA : 160895
B365>2.5 : 230878
B365<2.5 : 230878
P>2.5 : 232982
P<2.5 : 232982
Max>2.5 : 232863
Max<2.5 : 232863
Avg>2.5 : 232863
Avg<2.5 : 232863
AHh : 232864
B365AHH : 230050
B365AHA : 230051
PAHH : 232955
PAHA : 232954
MaxAHH : 232863
MaxAHA : 232863
AvgAHH : 232863
AvgAHA : 232863
B365CH : 232883
B365CD : 232883
B365CA : 232883
BWCH : 232978
BWCD : 232978
BWCA : 232978
IWCH : 232922
IWCD : 232922
IWCA : 232922
PSCH : 198083
PSCD : 198084
PSCA : 198084
WHCH : 233334
WHCD : 233334
WHCA : 233334
VCCH : 232872
VCCD : 232872
VCCA : 232872
MaxCH : 232855
MaxCD : 232855
MaxCA : 232855
AvgCH : 232855
AvgCD : 232855
AvgCA : 232855
B365C>2.5 : 232887
B365C<2.5 : 232887
PC>2.5 : 232885
PC<2.5 : 232885
MaxC>2.5 : 232855
MaxC<2.5 : 232855
AvgC>2.5 : 232855
AvgC<2.5 : 232855
AHCh : 232855
B365CAHH : 232901
B365CAHA : 232901
PCAHH : 232864
PCAHA : 232864
MaxCAHH : 232855
MaxCAHA : 232855
AvgCAHH : 232855
AvgCAHA : 232855
Unnamed: 105 : 250201
HFKC : 248867
AFKC : 248867
Bb1X2 : 177643
BbMxH : 177643
BbAvH : 177643
BbMxD : 177643
BbAvD : 177643
BbMxA : 177643
BbAvA : 177643
BbOU : 177689
BbMx>2.5 : 177690
BbAv>2.5 : 177690
BbMx<2.5 : 177691
BbAv<2.5 : 177691
BbAH : 177852
BbAHh : 177853
BbMxAHH : 177853
BbAvAHH : 177853
BbMxAHA : 177855
BbAvAHA : 177855
LBH : 172968
LBD : 172968
LBA : 172965
SJH : 203466
SJD : 203466
SJA : 203466
GBH : 190833
GBD : 190833
GBA : 190833
BSH : 219538
BSD : 219537
BSA : 219537
SBH : 198358
SBD : 198357
SBA : 198357
Unnamed: 58 : 250201
Unnamed: 59 : 250201
Unnamed: 60 : 250201
GB>2.5 : 241612
GB<2.5 : 241612
GBAHH : 244047
GBAHA : 244047
GBAH : 244049
B365AH : 247215
Unnamed: 39 : 250201
Unnamed: 40 : 250201
Unnamed: 41 : 250201
Unnamed: 42 : 250201
Unnamed: 43 : 250201
Unnamed: 30 : 250201
Unnamed: 31 : 250201
Unnamed: 32 : 250201
Unnamed: 33 : 250201
Unnamed: 34 : 250201
Unnamed: 35 : 250201
Unnamed: 36 : 250201
Unnamed: 37 : 250201
Unnamed: 38 : 250201
Unnamed: 44 : 250201
Unnamed: 45 : 250201
Unnamed: 46 : 250201
Unnamed: 47 : 250201
Unnamed: 48 : 250201
SYH : 246653
SYD : 246653
SYA : 246653
Unnamed: 25 : 250201
Unnamed: 26 : 250201
Unnamed: 10 : 250201
Unnamed: 11 : 250201
Unnamed: 12 : 250201
Unnamed: 13 : 250201
Unnamed: 14 : 250201
Unnamed: 15 : 250201
Unnamed: 16 : 250201
Unnamed: 17 : 250201
Unnamed: 18 : 250201
Unnamed: 19 : 250201
Unnamed: 20 : 250201
LBAHH : 247921
LBAHA : 247921
LBAH : 247921
Unnamed: 49 : 250201
Unnamed: 50 : 250201
SOH : 247934
SOD : 247934
SOA : 247934
Unnamed: 7 : 250201
Unnamed: 8 : 250201
Unnamed: 9 : 250201
Unnamed: 21 : 250201
Unnamed: 22 : 250201
Unnamed: 23 : 250201
Unnamed: 24 : 250201
Unnamed: 27 : 250201
Unnamed: 70 : 250201
Unnamed: 71 : 250201
Unnamed: 72 : 250201
Unnamed: 54 : 250201
Unnamed: 55 : 250201
Unnamed: 56 : 250201
Unnamed: 57 : 250201
Unnamed: 61 : 250201
Unnamed: 62 : 250201
LB : 250099
LB.1 : 250099
LB.2 : 250099
Attendance : 247453
Referee : 239933
HHW : 247618
AHW : 247618
HO : 247617
AO : 247617
HBP : 247446
ABP : 247446
HT : 249155
AT : 249155
Unnamed: 28 : 250201
Unnamed: 29 : 250201
Unnamed: 51 : 250201
Unnamed: 106 : 250201
Unnamed: 52 : 250201
Unnamed: 53 : 250201

,Country,League,Season,Date,Time,Home,Away,PH,PD,PA,...,HBP,ABP,HT,AT,Unnamed: 28,Unnamed: 29,Unnamed: 51,Unnamed: 106,Unnamed: 52,Unnamed: 53
0,Argentina,Liga Profesional,2012/2013,03/08/2012,23:00,Arsenal Sarandi,Union de Santa Fe,1.90,3.39,5.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Argentina,Liga Profesional,2012/2013,04/08/2012,01:10,Velez Sarsfield,Argentinos Jrs,2.00,3.24,4.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Argentina,Liga Profesional,2012/2013,04/08/2012,18:10,Racing Club,Atl. Rafaela,1.91,3.34,5.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Argentina,Liga Profesional,2012/2013,04/08/2012,20:10,Colon Santa FE,Lanus,2.50,3.16,3.27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,Liga Profesional,2012/2013,04/08/2012,22:15,Quilmes,Boca Juniors,3.18,3.13,2.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8461,USA,MLS,2022,23/10/2022,18:00,CF Montreal,New York City,2.12,3.45,3.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8462,USA,MLS,2022,24/10/2022,01:00,Austin FC,FC Dallas,2.30,3.49,3.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8463,USA,MLS,2022,30/10/2022,19:00,Los Angeles FC,Austin FC,1.49,4.80,6.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8464,USA,MLS,2022,31/10/2022,00:00,Philadelphia Union,New York City,1.97,3.67,4.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8465,USA,MLS,2022,05/11/2022,20:00,Los Angeles FC,Philadelphia Union,1.71,4.13,4.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
premier_league_df = df.loc[df['Div'] == 'E0']
df = df.loc[df['Div'] != 'E0']
premier_league_df

In [75]:
# columns_to_drop = ['Country', 'League', 'Season', 'Date', 'Time', 
                  # 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'HTHG',
                  # 'HTAG', 'HTR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
                  # 'BWA', 'IWH', 'IWD', 'IWA', 'WHH', 'WHD', 'WHA', 'VCH',
                  # 'VCD', 'VCA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5',
                  # 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH',
                  # 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH',
                  # 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD',
                  # 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'WHCH', 'WHCD', 'WHCA',
                  # 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH',
                  # 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5',
                  # 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh',
                  # 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
                  # 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'HFKC', 'AFKC', 'Bb1X2',
                  # 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
                  # 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5',
                  # 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
                  # 'LBH', 'LBD', 'LBA', 'SJH', 'SJD', 'SJA', 'GBH', 'GBD',
                  # 'GBA', 'BSH', 'BSD', 'BSA', 'SBH', 'SBD', 'SBA', 'GB>2.5',
                  # 'GB<2.5', 'GBAHH', 'GBAHA', 'GBAH']

columns_to_keep = ['Home', 'Away', 'PH', 'PD', 'PA', 'FTHG', 'FTAG', 'FTR', 'PSCH', 'PSCD', 'PSCA']

for column in df:
  if column not in columns_to_keep:
    df = df.drop(column, axis=1)

df

,Home,Away,PH,PD,PA,FTHG,FTAG,FTR,PSCH,PSCD,PSCA
0,Arsenal Sarandi,Union de Santa Fe,1.90,3.39,5.03,1.0,0.0,H,NaN,NaN,NaN
1,Velez Sarsfield,Argentinos Jrs,2.00,3.24,4.55,3.0,0.0,H,NaN,NaN,NaN
2,Racing Club,Atl. Rafaela,1.91,3.34,5.09,1.0,1.0,D,NaN,NaN,NaN
3,Colon Santa FE,Lanus,2.50,3.16,3.27,1.0,0.0,H,NaN,NaN,NaN
4,Quilmes,Boca Juniors,3.18,3.13,2.58,3.0,0.0,H,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8461,CF Montreal,New York City,2.12,3.45,3.75,1.0,3.0,A,NaN,NaN,NaN
8462,Austin FC,FC Dallas,2.30,3.49,3.25,2.0,1.0,H,NaN,NaN,NaN
8463,Los Angeles FC,Austin FC,1.49,4.80,6.59,3.0,0.0,H,NaN,NaN,NaN
8464,Philadelphia Union,New York City,1.97,3.67,4.02,3.0,1.0,H,NaN,NaN,NaN
8465,Los Angeles FC,Philadelphia Union,1.71,4.13,4.89,3.0,3.0,D,NaN,NaN,NaN

In [76]:
for column in df:
  print(column, ':', df[column].isna().sum())

Home : 20064
Away : 20064
PH : 106093
PD : 106093
PA : 106093
FTHG : 19022
FTAG : 19022
FTR : 19022
PSCH : 198083
PSCD : 198084
PSCA : 198084

In [77]:
df = df[df['PSCH'].notna()]
df[['PCH', 'PCD', 'PCA']] = df[['PSCH', 'PSCD', 'PSCA']]
df = df.drop(['PSCH', 'PSCD', 'PSCA'], axis=1)
df

C:\Users\CARBON~1\AppData\Local\Temp/ipykernel_1920/3689975407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PCH', 'PCD', 'PCA']] = df[['PSCH', 'PSCD', 'PSCA']]
C:\Users\CARBON~1\AppData\Local\Temp/ipykernel_1920/3689975407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PCH', 'PCD', 'PCA']] = df[['PSCH', 'PSCD', 'PSCA']]
C:\Users\CARBON~1\AppData\Local\Temp/ipykernel_1920/3689975407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PCH', 'PCD', 'PCA']] = df[['PSCH', 'PSCD', 'PSCA']]

,Home,Away,PH,PD,PA,FTHG,FTAG,FTR,PCH,PCD,PCA
0,Standard,Gent,4.27,3.67,1.89,2.0,2.0,D,4.36,3.58,1.90
1,Charleroi,Eupen,1.68,4.35,4.69,3.0,1.0,H,1.66,4.26,5.01
2,Kortrijk,Oud-Heverlee Leuven,2.47,3.65,2.81,0.0,2.0,A,2.4,3.45,3.06
3,Waregem,Seraing,2.20,3.83,3.14,2.0,0.0,H,1.96,3.54,4.13
4,St Truiden,St. Gilloise,4.13,3.62,1.93,1.0,1.0,D,3.65,3.06,2.31
...,...,...,...,...,...,...,...,...,...,...,...
3376,Orduspor,Akhisar Belediyespor,4.08,3.01,2.23,0.0,2.0,A,3.67,3.13,2.31
3377,Elazigspor,Sivasspor,2.42,3.47,3.02,0.0,0.0,D,2.52,3.32,3.06
3378,Eskisehirspor,Antalyaspor,2.18,3.56,3.44,3.0,1.0,H,1.93,3.60,4.37
3379,Genclerbirligi,Bursaspor,2.48,3.51,2.92,2.0,2.0,D,1.93,3.60,4.37
3380,Kayserispor,Besiktas,2.59,3.55,2.76,2.0,0.0,H,2.72,3.65,2.61

In [78]:
df = df.reset_index(drop=True)
df

,Home,Away,PH,PD,PA,FTHG,FTAG,FTR,PCH,PCD,PCA
0,Standard,Gent,4.27,3.67,1.89,2.0,2.0,D,4.36,3.58,1.90
1,Charleroi,Eupen,1.68,4.35,4.69,3.0,1.0,H,1.66,4.26,5.01
2,Kortrijk,Oud-Heverlee Leuven,2.47,3.65,2.81,0.0,2.0,A,2.4,3.45,3.06
3,Waregem,Seraing,2.20,3.83,3.14,2.0,0.0,H,1.96,3.54,4.13
4,St Truiden,St. Gilloise,4.13,3.62,1.93,1.0,1.0,D,3.65,3.06,2.31
...,...,...,...,...,...,...,...,...,...,...,...
52113,Orduspor,Akhisar Belediyespor,4.08,3.01,2.23,0.0,2.0,A,3.67,3.13,2.31
52114,Elazigspor,Sivasspor,2.42,3.47,3.02,0.0,0.0,D,2.52,3.32,3.06
52115,Eskisehirspor,Antalyaspor,2.18,3.56,3.44,3.0,1.0,H,1.93,3.60,4.37
52116,Genclerbirligi,Bursaspor,2.48,3.51,2.92,2.0,2.0,D,1.93,3.60,4.37
52117,Kayserispor,Besiktas,2.59,3.55,2.76,2.0,0.0,H,2.72,3.65,2.61

In [79]:
for column in df:
  print(column, ':', df[column].isna().sum())

df = df.dropna()

for column in df:
  print(column, ':', df[column].isna().sum())

Home : 1
Away : 1
PH : 684
PD : 684
PA : 684
FTHG : 2
FTAG : 2
FTR : 2
PCH : 0
PCD : 1
PCA : 1
Home : 0
Away : 0
PH : 0
PD : 0
PA : 0
FTHG : 0
FTAG : 0
FTR : 0
PCH : 0
PCD : 0
PCA : 0

In [80]:
df.to_csv('./cleaned_data/cleaned_data.csv')